@startuml
!include <kubernetes/k8s-sprites-unlabeled-25pct>

node "Notification" {
  interface "Knative events listener" as keventingi
  component "<$node>\nKnative Eventing" as keventing
}

node "Automation" {
  component "<$node>\nArgo Events" as aevents
  component "ZOO OGC API Processes" as zoo
}

keventingi -d-> keventing

keventing -> aevents : POST cloudevents payload
aevents -> zoo : POST cloudevents\nto OGC Process\ntransformed message
zoo -> aevents : POST OGC Processes\nexecution results\nto callback URL
aevents -> keventing : POST OGC Processes\nexecution results to cloudevents\ntransformed message

@enduml
