@startuml
!include <kubernetes/k8s-sprites-unlabeled-25pct>
autonumber "<b>[00]"

participant "<$node>\nKnative Eventing" as keventing

box "Argo Events"
  participant "Webhook event-source\ncloudevents entry point" as aewhi
  participant "HTTP Trigger\ncloudevents to OGC Process" as aehti

  participant "HTTP Trigger\nOGC Process to cloudevents" as aehto
  participant "Webhook event-source\nOGC Process entry point" as aewho
end box

participant "ZOO OGC API Processes" as zoo

== Process request ==

keventing -> aewhi ++ : POST a cloudevents describing a new acquisition
aewhi --> keventing : ACK
aewhi -> aehti ++ : Forward the cloudevents describing the new acquisition
aehti -> aehti: Transform the input cloudevents to OGC Process execute request\nAdd the internal callback URL parameter
deactivate aewhi

aehti -> zoo ++ : POST OGC Process
zoo --> aehti -- : ACK
deactivate aehti

== Asynchronous Process response ==

' this is a workaround to avoid multiple times activation error
zoo -[hidden]> aewho

activate zoo
zoo -> aewho ++ : POST the Process result to the internal callback URL
aewho --> zoo : ACK
deactivate zoo

aewho -> aehto ++ : Forward the OGC Process execution result to be submitted to Knative Eventing
aehto -> aehto : Transform the OGC Process result to cloudevents
deactivate aewho

aehto -> keventing ++ : Submit cloudevents representing the OGC Process result to the callback URL
keventing --> aehto -- : ACK
deactivate aehto

@enduml
